mainapp/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from .views import (
    BaseView,
    ProductDetailView,
    CategoryDetailView,
    CartView,
    AddToCartView,
    DeleteFromCartView,
    ChangeQuantityView,
    CheckoutView,
    MakeOrderView,
    LoginView,
    RegistrationView,
    OrderView,
    ProfileView,
)
from . import views


urlpatterns = [
    path('', BaseView.as_view(), name='base'),
    path('products/<str:slug>/', ProductDetailView.as_view(), name='product_detail'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category_detail'),
    path('cart/', CartView.as_view(), name='cart'),
    path('add-to-cart/<str:slug>/', AddToCartView.as_view(), name='add_to_cart'),
    path('remove-from-cart/<str:slug>/', DeleteFromCartView.as_view(), name='delete_from_cart'),
    path('change-quantity/<str:slug>/', ChangeQuantityView.as_view(), name='change_quantity'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('make-order/', MakeOrderView.as_view(), name='make_order'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page="/"), name='logout'),
    path('registration/', RegistrationView.as_view(), name='registration'),
    path('my_orders/', OrderView.as_view(), name='my_orders'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('profile_edit/', views.profile, name='profile_edit'),
]

minishop/urls.py
import os
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainapp.urls')),
    path('product-specs/', include('specs.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

specs/urls.py
from django.urls import path
from .views import (
    BaseSpecView,
    CreateNewFeature,
    CreateNewCategory,
    CreateNewFeatureValidator,
    FeatureChoiceView,
    CreateFeatureView,
    NewProductFeatureView,
    SearchProductAjaxView,
    AttachNewFeatureToProduct,
    ProductFeatureChoicesAjaxView,
    CreateNewProductFeatureAjaxView,
    UpdateProductFeaturesView,
    ShowProductFeaturesForUpdate,
    UpdateProductFeaturesAjaxView

)


urlpatterns = [
    path('', BaseSpecView.as_view(), name='product-list-for-features'),
    path('new-feature/', CreateNewFeature.as_view(), name='new-feature'),
    path('new-category/', CreateNewCategory.as_view(), name='new-category'),
    path('new-validator/', CreateNewFeatureValidator.as_view(), name='new-validator'),
    path('feature-choice/', FeatureChoiceView.as_view(), name='feature-choice-validators'),
    path('feature-create/', CreateFeatureView.as_view(), name='create-feature'),
    path('new-product-feature/', NewProductFeatureView.as_view(), name='new-product-feature'),
    path('search-product/', SearchProductAjaxView.as_view(), name='search-product'),
    path('attach-feature/', AttachNewFeatureToProduct.as_view(), name='attach-feature'),
    path('product-feature/', ProductFeatureChoicesAjaxView.as_view(), name='product-feature'),
    path('attach-new-product-feature/', CreateNewProductFeatureAjaxView.as_view(), name='attach-new-product-feature'),
    path('update-product-features/', UpdateProductFeaturesView.as_view(), name='update-product-features'),
    path('show-product-features-for-update/', ShowProductFeaturesForUpdate.as_view(), name='show-product-features-for-update'),
    path('update-product-features-ajax/', UpdateProductFeaturesAjaxView.as_view(), name='update-product-features-ajax'),
]

mainapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.urls import reverse
from django.utils import timezone


User = get_user_model()


class Category(models.Model):

    name = models.CharField(max_length=255, verbose_name='Имя категории')
    slug = models.SlugField(unique=False)

    def __str__(self):
        return self.name
    
    def get_absolute_url(self):
        return reverse('category_detail', kwargs={'slug': self.slug})


class Product(models.Model):

    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    title = models.CharField(max_length=255, verbose_name='Наименование')
    slug = models.SlugField(unique=False)
    image = models.ImageField(verbose_name='Изображение')
    description = models.TextField(verbose_name='Описание', null=True)
    price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Цена')
    features = models.ManyToManyField("specs.ProductFeatures", blank=True, related_name='features_for_product')


    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('product_detail', kwargs={'slug': self.slug})
    
    def get_features(self):
            return {f.feature.feature_name: ' '.join([f.value, f.feature.unit or ""]) for f in self.features.all()}

    def safe(self, *args, **kwargs):
        super().save(*args, **kwargs)


class CartProduct(models.Model):

    user = models.ForeignKey('Customer', verbose_name='Покупатель', on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', verbose_name='Корзина', on_delete=models.CASCADE, related_name='related_product')
    product = models.ForeignKey(Product, verbose_name='Товар', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    total_price = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Общая цена')

    def __str__(self):
        return "Продукт: {} (для корзины)".format(self.product.title)

    def save(self, *args, **kwargs):
        self.total_price = self.quantity * self.product.price
        super().save(*args, **kwargs)


class Cart(models.Model):

    owner = models.ForeignKey('Customer',null=True, verbose_name='Владелец', on_delete=models.CASCADE)
    products = models.ManyToManyField(CartProduct, blank=True, related_name='related_cart')
    total_products = models.PositiveIntegerField(default=0)
    total_price = models.DecimalField(max_digits=9, decimal_places=2, default=0, verbose_name='Общая цена')
    in_order = models.BooleanField(default=False)
    for_anonymous_user = models.BooleanField(default=False)

    def __str__(self):
        return str(self.id)


class Customer(models.Model):

    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    phone = models.CharField(max_length=13, verbose_name='Номер телефона', null=True, blank=True)
    address = models.CharField(max_length=255, verbose_name='Адрес', null=True, blank=True)
    orders = models.ManyToManyField('Order', verbose_name='Заказы покупателя', related_name='related_customer')

    def __str__(self):
        return "Покупатель: {} {}".format(self.user.first_name, self.user.last_name)


class Order(models.Model):

    STATUS_NEW = 'new'
    STATUS_IN_PROGRESS = 'in_progress'
    STATUS_READY = 'is_ready'
    STATUS_COMPLETED = 'completed'

    BUYING_TYPE_SELF = 'self'
    BUYING_TYPE_DELIVERY = 'delivery'

    STATUS_CHOICES = (
        (STATUS_NEW, 'Новый заказ'),
        (STATUS_IN_PROGRESS, 'Заказ в обработке'),
        (STATUS_READY, 'Заказ готов'),
        (STATUS_COMPLETED, 'Заказ выполнен'),
    )

    BUYING_TYPE_CHOICES = (
        (BUYING_TYPE_SELF, 'Самовывоз'),
        (BUYING_TYPE_DELIVERY, 'Доствка')
    )

    customer = models.ForeignKey(Customer, verbose_name='Покупатель',related_name='related_orders' , on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255, verbose_name='Имя')
    last_name = models.CharField(max_length=255, verbose_name='Фамилия')
    phone = models.CharField(max_length=10, verbose_name='Телефон')
    cart = models.ForeignKey(Cart, verbose_name='Корзина', on_delete=models.CASCADE, null=True, blank=True)
    address = models.CharField(max_length=1024, verbose_name='Адрес', null=True, blank=True)
    status = models.CharField(
        max_length=100,
        verbose_name='Статус заказа',
        choices=STATUS_CHOICES,
        default=STATUS_NEW
        )
    buying_type = models.CharField(
        max_length=100,
        verbose_name='Тип заказа',
        choices=BUYING_TYPE_CHOICES,
        default=BUYING_TYPE_SELF
        )
    comment = models.TextField(verbose_name='Комментарий к заказу', null=True, blank=True)
    created_at = models.DateTimeField(auto_now=True, verbose_name='Дата создания заказа')
    order_date = models.DateField(verbose_name='Дата получения закза', default=timezone.now)

    def __str__(self):
        return str(self.id)

mainapp/forms.py
from django import forms
from .models import Order
from django.contrib.auth.models import User


class OrderForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['order_date'].label = 'Дата получния заказа'

    order_date = forms.DateField(widget=forms.TextInput(attrs={'type': 'date'}))

    class Meta:
        model = Order
        fields = (
            'first_name', 'last_name', 'phone', 'address', 'buying_type', 'order_date', 'comment'
        )


class LoginForm(forms.ModelForm):

    password = forms.CharField(widget=forms.PasswordInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        if not User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Пользователь с логином {username} не найден в системе.')
        user = User.objects.filter(username=username).first()
        if user:
            if not user.check_password(password):
                raise forms.ValidationError("Неверный пароль")
        return self.cleaned_data

    class Meta:
        model = User
        fields = ['username', 'password']


class RegistationForm(forms.ModelForm):

    confirm_password = forms.CharField(widget=forms.PasswordInput)
    password = forms.CharField(widget=forms.PasswordInput)
    phone = forms.CharField(required=False)
    address = forms.CharField(required=False)
    email = forms.EmailField(required=True)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)        
        self.fields['username'].label = 'Логин'
        self.fields['password'].label = 'Пароль'
        self.fields['confirm_password'].label = 'Подтвердите пароль'
        self.fields['phone'].label = 'Номер телефона'
        self.fields['first_name'].label = 'Имя'
        self.fields['last_name'].label = 'Фамилия'
        self.fields['address'].label = 'Адрес'
        self.fields['email'].label = 'Эл. адрес'
    
    def clean_email(self):
        email = self.cleaned_data['email']
        domain = email.split('.')[-1]
        if domain in ['com', 'net']:
            raise forms.ValidationError(f'Регистрация для домена "{domain}" невозможна.')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError(f'Данный почтовый адрес уже зарегистрирован.')
        return email
    
    def clean_username(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError(f'Пользователь с именем {username} уже существует.')
        return username
    
    def clean(self):
        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError(f'Пароли не совпадают')
        return self.cleaned_data
    
    class Meta:
        model = User
        fields = ['username', 'password', 'confirm_password', 'first_name', 'last_name', 'address', 'phone', 'email',]


class ProfileEditForm(forms.ModelForm):

    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    confirm_password = forms.CharField(label='Подтвердите пароль', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password(self):
        password = self.cleaned_data.get("password")
        confirm_password = self.cleaned_data.get("confirm_password")
        if password and confirm_password and password != confirm_password:
            print("Пароли не свпадают")
            raise forms.ValidationError("Пароли не совпадают")
        print("confirm_password")
        return confirm_password

    def save(self, commit=True):
        user = super(ProfileEditForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            print("save")
            user.save()
        print("user")
        return user

mainapp/templates/mainapp/admin.html
{% extends 'admin/change_form.html' %}
{% load static %}

{% block admin_change_form_document_ready %}
{{ block.super }}

<script>
    (function($) {
        $('#id_is_camera_front').on('click', function(){
            if($('#id_is_camera_front').prop('checked') == true){
                $('#id_camera_front').prop('readonly', false)
                $('#id_camera_front').val('')
                $('$id_camera_front').css('background', 'white')
            }else{
                $('#id_camera_front').prop('readonly', true)
                $('#id_camera_front').val('')
                $('#id_camera_front').css('background', 'lightgray')
            }
        })
    })(django.jQuery);
</script>

{% endblock %}

mainapp/templates/mainapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>MiniShop for Intern</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <!-- Custom styles for this template -->
  <link href="css/shop-homepage.css" rel="stylesheet">

</head>

<style>
  body {
    padding-top: 56px;
  }
</style>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container">
      <a class="navbar-brand" href="{% url 'base' %}" style="color: azure;">MiniShop</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav">
          <li class="nav-item dropdown">
            <a class="nav-link text-light dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expended="false">
              Категории
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              {% for category in categories %}
              <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
              {% endfor %}
            </div>
          </li>
          {% if not request.user.is_authenticated %}
          <li>
            <a class="nav-link text-light" href="{% url 'login' %}">Авторизация</a>
          </li>
          <li>
            <a class="nav-link text-light" href="{% url 'registration' %}">Регистрация</a>
          </li>
          {% endif %}
          <li class="nav-item">
            {% if request.user.is_authenticated %}
            <span class="navbar text text-light">Здравствуйте, 
                <li class="nav-item dropdown">
                  <a class="nav-link text-light dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expended="false">
                    {{ request.user.first_name }}
                  </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                      <a class="dropdown-item" href="{% url 'profile' %}">Учетная запись</a>
                      <a class="dropdown-item" href="{% url 'my_orders' %}">Мои заказы</a>
                      {% if request.user.username == 'admin' %}
                      <a class="dropdown-item" href="/product-specs/">Редактирование товаров</a>
                      {% endif%}
                    </div>
                  </div>
                </li>
                <a style="text-decoration: none; color: white; text-decoration: none; font-size: 14px;" href="{% url 'logout' %}">Выйти</a>
            </span>
            {% endif %}
          </li>
        </ul>
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'cart' %}">Корзина <span class="badge badge-pill badge-danger">{{ cart.products.count }}</span></a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Page Content -->
  <div class="container">

    <div class="row">

      <div class="col-lg-3 mt-5">

        <div class="list-group">
          {% for category in categories %}
          <a href="{{ category.get_absolute_url }}" class="list-group-item">{{ category.name }} ({{ category.product_set.count }})</a>
          {% endfor %}

        </div>
      {% block productfilter %}
      {% endblock productfilter %}
      </div>
      <!-- /.col-lg-3 -->

      <div class="col-lg-9">

        {% block content %}

        {% if messages %}
          {% for message in messages %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                <strong>{{ message }}</strong>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
                </button>
            </div>
          {% endfor %}
        {% endif %}

        <div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
            <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
          </ol>
          <div class="carousel-inner" role="listbox">
            <div class="carousel-item active">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
            </div>
            <div class="carousel-item">
              <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
            </div>
          </div>
          <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>

        <div class="row">

          {% for product in products %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card h-100">
              <a href="{{ product.get_absolute_url }}"><img class="card-img-top" src="{{ product.image.url }}" alt=""></a>
              <div class="card-body">
                <h4 class="card-title">
                  <a href="{{ product.get_absolute_url }}">{{ product.title }}</a>
                </h4>
                <h5>{{ product.price }} сом</h5>
                <a href="{% url 'add_to_cart' slug=product.slug %}">
                  <button class="btn btn-danger">Добавить в корзину</button>
                </a>
              </div>
            </div>
          </div>
          {% endfor %}

        </div>
        <!-- /.row -->

      {% endblock content %}

      </div>
      <!-- /.col-lg-9 -->

    </div>
    <!-- /.row -->

  </div>
  <!-- /.container -->

  <!-- Footer -->
  <footer class="py-5 bg-dark">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Elmar Azimkulov 2021</p>
    </div>
    <!-- /.container -->
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>

</html>

mainapp/templates/mainapp/cart.html
{% extends 'mainapp/base.html' %}


{% block content %}

<nav aria-label="breadcrumb" class="mt-3">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'base' %}">Главная</a></li>
    </ol>
</nav>

<h3 class="text-center mb-3">Ваша корзина{% if not cart.products.count %} пуста{% endif %}</h3>
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <strong>{{ message }}</strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endfor %}
{% endif %}
{% if cart.products.count %}
<table class="table">
    <thead>
        <tr>
            <th scope="col">Наименование</th>
            <th scope="col">Изображение</th>
            <th scope="col">Цена</th>
            <th scope="col">Количество</th>
            <th scope="col">Общая цена</th>
            <th scope="col">Действие</th>
        </tr>
    </thead>
    <tbody>

        {% for item in cart.products.all %}
        <tr>
            <th scope="row">{{ item.product.title }}</th>
            <td class="w-25"><img src="{{ item.product.image.url }}" class="img-fluid"></td>
            <td>{{ item.product.price }} сом</td>
            <td>
                <form action="{% url 'change_quantity' slug=item.product.slug %}" method="POST">
                    {% csrf_token %}
                    <input type="number" class="form-control" name="quantity" style="width: 70px;" min="1" value="{{ item.quantity }}">
                    <br>
                    <input type="submit" class="btn btn-primary" value="Изменить количество">
                </form>
            </td>
            <td>{{ item.total_price }} сом</td>
            <td>
                <a href="{% url 'delete_from_cart' slug=item.product.slug %}"><button class="btn btn-danger">Удалить из корзины</button></a>
            </td>
        </tr>
        {% endfor %}

        <tr>
            <td colspan="2"></td>
            <td>Итого: </td>
            <td>{{ cart.total_products }}</td>
            <td>{{ cart.total_price }}</td>
            <td>
                <a href="{% url 'checkout' %}">
                    <button class="btn btn-primary">
                        Перейти к оформлению
                    </button>
                </a>
            </td>
        </tr>

    </tbody>
  </table>

{% endif %}
{% endblock content %}

mainapp/templates/mainapp/checkout.html
{% extends 'mainapp/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<h3 class="text-center mt-2 mb-3">Оформление заказа</h3>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Наименование</th>
            <th scope="col">Изображение</th>
            <th scope="col">Цена</th>
            <th scope="col">Количество</th>
            <th scope="col">Общая цена</th>
        </tr>
    </thead>
    <tbody>

        {% for item in cart.products.all %}
        <tr>
            <th scope="row">{{ item.product.title }}</th>
            <td class="w-25"><img src="{{ item.product.image.url }}" class="img-fluid"></td>
            <td>{{ item.product.price }} сом</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.total_price }} сом</td>
        </tr>
        {% endfor %}

        <tr>
            <td colspan="2"></td>
            <td>Итого: </td>
            <td>{{ cart.total_products }}</td>
            <td>{{ cart.total_price }}</td>
        </tr>

    </tbody>
</table>
<hr>
<h3 class="text-center mt-2 mb-3">Форма заказа</h3>
<form action="{% url 'make_order' %}" method="POST">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" class="btn btn-success btn-block mb-3" value="Оформить заказ">
</form>

{% endblock content %}

mainapp/templates/mainapp/my_orders.html
{% extends 'mainapp/base.html' %}


{% block content %}

<h3 class="mt-3 mb-3">Заказы пользователя {{ request.user.username }}</h3>
{% if not orders.count %}
<div class="col-md-12" style="margin-top: 300px; margin-bottom: 300px;">
    <h3>У вас еще нет заказов. <a href="{% url 'base' %}">Перейдите в магазин.</a></h3>
</div>
{% else %}
<div class="col-md-12" style="margin-bottom:250px; margin-top: 250px;">
<table class="table">
    <thead>
        <th scope="col">Номер</th>
        <th scope="col">Статус</th>
        <th scope="col">Сумма</th>
        <th scope="col">Товар</th>
        <th scope="col">Допольнительно</th>
    </thead>
    <tbody>
{% for order in orders %}
<tr>
    <th scope="row">{{ order.id }}</th>
    <td>{{ order.get_status_display }}</td>
    <td>{{ order.cart.total_price }} сом</td>
    <td>
        <ul>
            {% for item in order.cart.products.all %}
            <li>{{ item.product.title }} x {{ item.quantity }}</li>
            {% endfor %}
        </ul>
    </td>
    <td>
        <button class="btn btn-info" data-toggle="modal" data-target="#exampleModal-{{ order.id }}">Допольнительно</button>
        <div class="modal fade" id="exampleModal-order.id" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLabel">Детализация заказа</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <h4 class="text-center">Товар</h4>
                  <table class="table">
                      <thead>
                          <tr>
                              <th scope="col">Наименование</th>
                              <th scope="col">Изображение</th>
                              <th scope="col">Цена</th>
                              <th scope="col">Количество</th>
                              <th scope="col">Общая цена</th>
                          </tr>
                      </thead>
                      <tbody>
                          {% for item in order.cart.products.all %}
                            <tr>
                                <th class="row">{{ item.product.title }}</th>
                                <td class="w-25"><img src="{{ item.product.image.url }}" class="img-fluid"></td>
                                <td><strong>{{ item.product.price }}</strong> сом</td>
                                <td>{{ item.quantity }}</td>
                                <td>{{ item.total_price }} сом</td>
                            </tr>
                          {% endfor %}
                          <tr>
                              <td colspan="2"></td>
                              <td>Итого</td>
                              <td>{{ order.cart.total_products }}</td>
                              <td><strong>{{ order.cart.total_price }}</strong> сом</td>
                          </tr>
                      </tbody>
                  </table>
                  <hr>
                  <h4 class="text-center">Допольнительная информация</h4>
                  <p>Имя: <strong>{{ order.first_name }}</strong></p>
                  <p>Фамилия: <strong>{{ order.last_name }}</strong></p>
                  <p>Телефон: <strong>{{ order.customer.phone }}</strong></p>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                </div>
              </div>
            </div>
          </div>
    </td>
</tr>
{% endfor %}
    </tbody>
</table>
</div>

{% endif %}

{% endblock %}